-- Seed data for ingredients table
INSERT INTO ingredients (name, display_name) VALUES 
('flour', 'Flour'),
('sugar', 'Sugar'),
('butter', 'Butter'),
('milk', 'Milk'),
('egg', 'Egg'),
('salt', 'Salt'),
('pepper', 'Pepper'),
('water', 'Water'),
('oil', 'Oil'),
('vinegar', 'Vinegar'),
('lemon_juice', 'Lemon Juice'),
('baking_powder', 'Baking Powder'),
('baking_soda', 'Baking Soda'),
('yeast', 'Yeast'),
('cinnamon', 'Cinnamon'),
('vanilla_extract', 'Vanilla Extract'),
('bread_flour', 'Bread Flour'),
('cake_flour', 'Cake Flour'),
('margarine', 'Margarine'),
('oatmeal', 'Oatmeal'),
('cocoa_powder', 'Cocoa Powder'),
('coconut', 'Coconut'),
('molasses', 'Molasses'),
('ground_cinnamon', 'Ground Cinnamon'),
('ground_cloves', 'Ground Cloves'),
('ground_ginger', 'Ground Ginger'),
('confectioners_sugar', 'Confectioners Sugar')
ON CONFLICT (name) DO NOTHING;